name: Build For Android

on:
  # Trigger on every pull request and on push
  # to the `main` branch.
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && (contains(github.ref, '/heads/master') || contains(github.ref, '/tags/v')))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: cd ./RemoteApp && npm install
      - name: Build the Web app
        run: npm run build
      - name: Build the Android app
        run: cd android && ./gradlew build
